[package]
name = "yew-mandelbrot"
version = "0.1.0"
authors = ["vitocchi <vitocchi.mm@gmail.com>"]
edition = "2018"

[dependencies]
yew = "0.18.0"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = [
    "HtmlCanvasElement",
    "CanvasRenderingContext2d",
    "ImageData"
]
